apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgreschart.name" . }}
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_USER: {{ printf .Values.secret.postgreschart.POSTGRES_USER | b64enc}}
  POSTGRES_PASSWORD: {{ printf .Values.secret.postgreschart.POSTGRES_PASSWORD | b64enc }}
  POSTGRES_DB: {{ printf .Values.secret.postgreschart.POSTGRES_DB | b64enc }}
