apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgreschart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgreschart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgreschart
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      protocol: TCP
  selector:
    {{- include "postgreschart.selectorLabels" . | nindent 4 }}
