# Default values for postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 14.0

service:
  type: NodePort
  port: 5432
  targetPort: 5432

ingress:
  enabled: false

persistence:
  enabled: true
  size: 100Gi

secret:
  indicatordb:
    POSTGRES_USER: myuser
    POSTGRES_PASSWORD: mypassword
    POSTGRES_DB: mydatabase

nodeSelector: {}

tolerations: []

affinity: {}
